name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"] 
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_analytics:
    staging:
      +materialized: view
      +dataset: ecommerce_staging
      
    intermediate:
      +materialized: view
      +dataset: ecommerce_intermediate
      
    marts:
      +materialized: table
      core:
        +dataset: ecommerce_core
      analytics:
        +dataset: ecommerce_analytics

seeds:
  ecommerce_analytics:
    +dataset: ecommerce_seeds

# BigQuery-specific configurations
vars:
  # Business configuration
  cohort_periods: 12
  rfm_quantiles: [0.2, 0.4, 0.6, 0.8]
  
  # BigQuery specific
  start_date: '2023-01-01'
  end_date: '2024-12-31'